/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 22-jul.-2026 10:26:03 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS alerta_id_alerta_seq
;

DROP SEQUENCE IF EXISTS categoria_id_categoria_seq
;

DROP SEQUENCE IF EXISTS cliente_id_cliente_seq
;

DROP SEQUENCE IF EXISTS detalle_pedido_id_detalle_pedido_seq
;

DROP SEQUENCE IF EXISTS detalle_venta_id_detalle_seq
;

DROP SEQUENCE IF EXISTS pedido_id_pedido_seq
;

DROP SEQUENCE IF EXISTS producto_id_producto_seq
;

DROP SEQUENCE IF EXISTS proveedor_id_proveedor_seq
;

DROP SEQUENCE IF EXISTS reporte_ventas_id_reporte_seq
;

DROP SEQUENCE IF EXISTS usuario_id_usuario_seq
;

DROP SEQUENCE IF EXISTS venta_id_venta_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS alerta CASCADE
;

DROP TABLE IF EXISTS categoria CASCADE
;

DROP TABLE IF EXISTS cliente CASCADE
;

DROP TABLE IF EXISTS detalle_pedido CASCADE
;

DROP TABLE IF EXISTS detalle_venta CASCADE
;

DROP TABLE IF EXISTS pedido CASCADE
;

DROP TABLE IF EXISTS producto CASCADE
;

DROP TABLE IF EXISTS proveedor CASCADE
;

DROP TABLE IF EXISTS reporte_venta_detalle CASCADE
;

DROP TABLE IF EXISTS reporte_ventas CASCADE
;

DROP TABLE IF EXISTS usuario CASCADE
;

DROP TABLE IF EXISTS venta CASCADE
;

/* Create Tables */

CREATE TABLE alerta
(
	id_alerta integer NOT NULL   DEFAULT NEXTVAL(('"alerta_id_alerta_seq"'::text)::regclass),
	tipo varchar(20) NOT NULL,
	fecha_generacion timestamp without time zone NOT NULL   DEFAULT now(),
	mensaje varchar(255) NOT NULL,
	id_producto integer NOT NULL,
	id_usuario integer NOT NULL
)
;

CREATE TABLE categoria
(
	id_categoria integer NOT NULL   DEFAULT NEXTVAL(('"categoria_id_categoria_seq"'::text)::regclass),
	nombre varchar(50) NOT NULL,
	estado boolean NOT NULL   DEFAULT true
)
;

CREATE TABLE cliente
(
	id_cliente integer NOT NULL   DEFAULT NEXTVAL(('"cliente_id_cliente_seq"'::text)::regclass),
	nombre varchar(100) NOT NULL,
	telefono varchar(20) NULL,
	numero_compras integer NOT NULL   DEFAULT 0,
	puntos integer NOT NULL   DEFAULT 0,
	estado boolean NOT NULL   DEFAULT true
)
;

CREATE TABLE detalle_pedido
(
	id_detalle_pedido integer NOT NULL   DEFAULT NEXTVAL(('"detalle_pedido_id_detalle_pedido_seq"'::text)::regclass),
	id_pedido integer NOT NULL,
	id_producto integer NOT NULL,
	cantidad_pedida integer NOT NULL
)
;

CREATE TABLE detalle_venta
(
	id_detalle integer NOT NULL   DEFAULT NEXTVAL(('"detalle_venta_id_detalle_seq"'::text)::regclass),
	id_venta integer NOT NULL,
	id_producto integer NOT NULL,
	cantidad integer NOT NULL,
	precio_unitario numeric(10,2) NOT NULL,
	subtotal numeric(10,2) NOT NULL
)
;

CREATE TABLE pedido
(
	id_pedido integer NOT NULL   DEFAULT NEXTVAL(('"pedido_id_pedido_seq"'::text)::regclass),
	fecha timestamp without time zone NOT NULL   DEFAULT now(),
	estado varchar(20) NOT NULL,
	id_usuario integer NOT NULL,
	id_proveedor integer NOT NULL
)
;

CREATE TABLE producto
(
	id_producto integer NOT NULL   DEFAULT NEXTVAL(('"producto_id_producto_seq"'::text)::regclass),
	nombre varchar(100) NOT NULL,
	precio_compra numeric(10,2) NOT NULL,
	precio_venta numeric(10,2) NOT NULL,
	stock integer NOT NULL   DEFAULT 0,
	stock_minimo integer NOT NULL   DEFAULT 5,
	fecha_vencimiento date NULL,
	id_categoria integer NOT NULL,
	url_imagen varchar(255) NULL,
	estado boolean NOT NULL   DEFAULT true
)
;

CREATE TABLE proveedor
(
	id_proveedor integer NOT NULL   DEFAULT NEXTVAL(('"proveedor_id_proveedor_seq"'::text)::regclass),
	nombre varchar(100) NOT NULL,
	contacto varchar(100) NULL,
	estado boolean NOT NULL   DEFAULT true
)
;

CREATE TABLE reporte_venta_detalle
(
	id_reporte integer NOT NULL,
	id_venta integer NOT NULL
)
;

CREATE TABLE reporte_ventas
(
	id_reporte integer NOT NULL   DEFAULT NEXTVAL(('"reporte_ventas_id_reporte_seq"'::text)::regclass),
	periodo varchar(20) NOT NULL,
	fecha_generacion timestamp without time zone NOT NULL   DEFAULT now(),
	total_ventas numeric(10,2) NOT NULL,
	ganancia_total numeric(10,2) NOT NULL,
	id_usuario integer NOT NULL
)
;

CREATE TABLE usuario
(
	id_usuario integer NOT NULL   DEFAULT NEXTVAL(('"usuario_id_usuario_seq"'::text)::regclass),
	nombre varchar(100) NOT NULL,
	login varchar(50) NOT NULL,
	contrasena varchar(255) NOT NULL,
	rol varchar(20) NOT NULL,
	estado boolean NOT NULL   DEFAULT true
)
;

CREATE TABLE venta
(
	id_venta integer NOT NULL   DEFAULT NEXTVAL(('"venta_id_venta_seq"'::text)::regclass),
	fecha timestamp without time zone NOT NULL   DEFAULT now(),
	total numeric(10,2) NOT NULL,
	id_usuario integer NOT NULL,
	id_cliente integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE alerta ADD CONSTRAINT "PK_alerta"
	PRIMARY KEY (id_alerta)
;

ALTER TABLE alerta ADD CONSTRAINT "CH_tipo" CHECK (tipo IN ('StockBajo','Vencimiento'))
;

CREATE INDEX "IXFK_alerta_producto" ON alerta (id_producto ASC)
;

CREATE INDEX "IXFK_alerta_usuario" ON alerta (id_usuario ASC)
;

ALTER TABLE categoria ADD CONSTRAINT "PK_categoria"
	PRIMARY KEY (id_categoria)
;

ALTER TABLE categoria 
  ADD CONSTRAINT "UQ_nombre" UNIQUE (nombre)
;

ALTER TABLE cliente ADD CONSTRAINT "PK_cliente"
	PRIMARY KEY (id_cliente)
;

ALTER TABLE detalle_pedido ADD CONSTRAINT "PK_detalle_pedido"
	PRIMARY KEY (id_detalle_pedido)
;

ALTER TABLE detalle_pedido ADD CONSTRAINT "CH_cantidad_pedida" CHECK (cantidad_pedida > 0)
;

CREATE INDEX "IXFK_detalle_pedido_pedido" ON detalle_pedido (id_pedido ASC)
;

CREATE INDEX "IXFK_detalle_pedido_producto" ON detalle_pedido (id_producto ASC)
;

ALTER TABLE detalle_venta ADD CONSTRAINT "PK_detalle_venta"
	PRIMARY KEY (id_detalle)
;

ALTER TABLE detalle_venta ADD CONSTRAINT "CH_cantidad" CHECK (cantidad > 0)
;

CREATE INDEX "IXFK_detalle_venta_producto" ON detalle_venta (id_producto ASC)
;

CREATE INDEX "IXFK_detalle_venta_venta" ON detalle_venta (id_venta ASC)
;

ALTER TABLE pedido ADD CONSTRAINT "PK_pedido"
	PRIMARY KEY (id_pedido)
;

ALTER TABLE pedido ADD CONSTRAINT "CH_estado" CHECK (estado IN ('Pendiente','Recibido','Cancelado'))
;

CREATE INDEX "IXFK_pedido_proveedor" ON pedido (id_proveedor ASC)
;

CREATE INDEX "IXFK_pedido_usuario" ON pedido (id_usuario ASC)
;

ALTER TABLE producto ADD CONSTRAINT "PK_producto"
	PRIMARY KEY (id_producto)
;

ALTER TABLE producto ADD CONSTRAINT "CH_precio_compra" CHECK (precio_compra  >= 0)
;

ALTER TABLE producto ADD CONSTRAINT "CH_precio_venta" CHECK (precio_venta >= 0)
;

ALTER TABLE producto ADD CONSTRAINT "CH_stock" CHECK (stock >= 0)
;

CREATE INDEX "IXFK_producto_categoria" ON producto (id_categoria ASC)
;

ALTER TABLE proveedor ADD CONSTRAINT "PK_proveedor"
	PRIMARY KEY (id_proveedor)
;

ALTER TABLE reporte_venta_detalle ADD CONSTRAINT "PK_reporte_venta_detalle"
	PRIMARY KEY (id_reporte,id_venta)
;

CREATE INDEX "IXFK_reporte_venta_detalle_reporte_ventas" ON reporte_venta_detalle (id_reporte ASC)
;

CREATE INDEX "IXFK_reporte_venta_detalle_venta" ON reporte_venta_detalle (id_venta ASC)
;

ALTER TABLE reporte_ventas ADD CONSTRAINT "PK_reporte_ventas"
	PRIMARY KEY (id_reporte)
;

ALTER TABLE reporte_ventas ADD CONSTRAINT "CH_periodo" CHECK (periodo IN ('Diario','Semanal','Mensual'))
;

CREATE INDEX "IXFK_reporte_ventas_usuario" ON reporte_ventas (id_usuario ASC)
;

ALTER TABLE usuario ADD CONSTRAINT "PK_usuario"
	PRIMARY KEY (id_usuario)
;

ALTER TABLE usuario 
  ADD CONSTRAINT "UQ_login" UNIQUE (login)
;

ALTER TABLE usuario ADD CONSTRAINT "CH_rol" CHECK (rol IN ('Administrador','Vendedor'))
;

ALTER TABLE venta ADD CONSTRAINT "PK_venta"
	PRIMARY KEY (id_venta)
;

ALTER TABLE venta ADD CONSTRAINT "CH_total" CHECK (total >= 0)
;

CREATE INDEX "IXFK_venta_cliente" ON venta (id_cliente ASC)
;

CREATE INDEX "IXFK_venta_usuario" ON venta (id_usuario ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE alerta ADD CONSTRAINT "FK_alerta_producto"
	FOREIGN KEY (id_producto) REFERENCES producto (id_producto) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE alerta ADD CONSTRAINT "FK_alerta_usuario"
	FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario) ON DELETE Restrict ON UPDATE No Action
;

ALTER TABLE detalle_pedido ADD CONSTRAINT "FK_detalle_pedido_pedido"
	FOREIGN KEY (id_pedido) REFERENCES pedido (id_pedido) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE detalle_pedido ADD CONSTRAINT "FK_detalle_pedido_producto"
	FOREIGN KEY (id_producto) REFERENCES producto (id_producto) ON DELETE Restrict ON UPDATE No Action
;

ALTER TABLE detalle_venta ADD CONSTRAINT "FK_detalle_venta_producto"
	FOREIGN KEY (id_producto) REFERENCES producto (id_producto) ON DELETE Restrict ON UPDATE No Action
;

ALTER TABLE detalle_venta ADD CONSTRAINT "FK_detalle_venta_venta"
	FOREIGN KEY (id_venta) REFERENCES venta (id_venta) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE pedido ADD CONSTRAINT "FK_pedido_proveedor"
	FOREIGN KEY (id_proveedor) REFERENCES proveedor (id_proveedor) ON DELETE Restrict ON UPDATE No Action
;

ALTER TABLE pedido ADD CONSTRAINT "FK_pedido_usuario"
	FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario) ON DELETE Restrict ON UPDATE No Action
;

ALTER TABLE producto ADD CONSTRAINT "FK_producto_categoria"
	FOREIGN KEY (id_categoria) REFERENCES categoria (id_categoria) ON DELETE Restrict ON UPDATE No Action
;

ALTER TABLE reporte_venta_detalle ADD CONSTRAINT "FK_reporte_venta_detalle_reporte_ventas"
	FOREIGN KEY (id_reporte) REFERENCES reporte_ventas (id_reporte) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE reporte_venta_detalle ADD CONSTRAINT "FK_reporte_venta_detalle_venta"
	FOREIGN KEY (id_venta) REFERENCES venta (id_venta) ON DELETE Restrict ON UPDATE No Action
;

ALTER TABLE reporte_ventas ADD CONSTRAINT "FK_reporte_ventas_usuario"
	FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario) ON DELETE Restrict ON UPDATE No Action
;

ALTER TABLE venta ADD CONSTRAINT "FK_venta_cliente"
	FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente) ON DELETE Set Null ON UPDATE No Action
;

ALTER TABLE venta ADD CONSTRAINT "FK_venta_usuario"
	FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario) ON DELETE Restrict ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE alerta_id_alerta_seq INCREMENT 1 START 1
;

CREATE SEQUENCE categoria_id_categoria_seq INCREMENT 1 START 1
;

CREATE SEQUENCE cliente_id_cliente_seq INCREMENT 1 START 1
;

CREATE SEQUENCE detalle_pedido_id_detalle_pedido_seq INCREMENT 1 START 1
;

CREATE SEQUENCE detalle_venta_id_detalle_seq INCREMENT 1 START 1
;

CREATE SEQUENCE pedido_id_pedido_seq INCREMENT 1 START 1
;

CREATE SEQUENCE producto_id_producto_seq INCREMENT 1 START 1
;

CREATE SEQUENCE proveedor_id_proveedor_seq INCREMENT 1 START 1
;

CREATE SEQUENCE reporte_ventas_id_reporte_seq INCREMENT 1 START 1
;

CREATE SEQUENCE usuario_id_usuario_seq INCREMENT 1 START 1
;

CREATE SEQUENCE venta_id_venta_seq INCREMENT 1 START 1
;
